### ISSUE TITLE
iss generate crashes when removing temporary files after execution

### ISSUE THREAD

**Issue by jdwinkler-lanzatech** [HadrienG/InSilicoSeq#143] opened 2019-12-27 18:47 UTC
Hi,

Thanks for developing this tool, it is quite useful. At the moment, I am having trouble with using iss with draft genomes; after generation of the synthetic reads and concatenation of the resulting fastq files into a single read pair, it looks like the the clean up function is trying to remove temporary fastq files that have already been deleted.

Upon examination, it looks like the R1 reads are being removed twice, and the try/except clause in the util.py/generate function exits upon the FileNotFoundException being raised by the os.remove call. I'm not exactly sure why this is happening. Any thoughts?

For the moment, I can work around this, but I imagine you could add an os.path.exists call before attempting to remove the files to avoid this scenario in the meantime.

Some log information:

INFO:iss.util:Cleaning up
ERROR:iss.util:Could not read temporary file: iss_synthetic_reads_10.iss.tmp.contig0.0_R1.fastq

**Comment by HadrienG** [comment] 2019-12-30 08:47
Hi!

Thanks for your bug report. I can't reproduce the error on my machine. Could you give me:

- your python version
- the output of `iss -v`
- the full input command
- your input file if not too large. If they are public genomes the accession numbers will do 😄 

Best,
/Hadrien

**Comment by jdwinkler-lanzatech** [comment] 2020-01-02 14:32
Sorry for the delayed reply-let me try to get this together this week. Unfortunately it seems like an intermittent error?

**Comment by HadrienG** [comment] 2020-01-21 06:39
Feel free to comment on this if it still happens, but so far I could not reproduce the bug so I'm closing this for now.

**Closed by HadrienG** 2020-01-21 06:39 UTC

**Comment by jdwinkler-lanzatech** [comment] 2020-01-21 14:29
Apologies, I eventually figured out that the OOM killer was terminating some of the read generating processes, which lead to unexplained failures at the read compression stage (since some of the expected files were missing, I think).
